### ISSUE TITLE
Feat: /education/lecture API

### ISSUE THREAD

**Issue by raae7742** [CPR2U/CPR2U-Server#1]
## ☝️  Issue
`/education/lecture` API 구현하겠읍니다

## 📃 To-do
- [x] `/education` 학습 화면 API
- [x] `/education/lecture` 강의 진도 조회 API
- [x] `/education/lecture/progress` 이수 완료 API
