### ISSUE TITLE
Fix: education API

### ISSUE THREAD

**Issue by raae7742** [CPR2U/CPR2U-Server#11]
## ☝️  Issue
/education API QA

## 📃 To-do
- [x] `/education/quizzes/progress` POST API: 통과 실패 시 200 상태 코드 리턴
- [x] `/education/exercises/progress` POST API: 통과 실패 시 200 상태 코드 리턴
- [x] `/education` GET API: progress_all → progress_percent로 변수명 변경
- [x] `/education` GET API: 사용자의 엔젤 상태 정수값(0, 1, 2)으로 반환 및 response 설명에 엔젤 상태 종류 달기
- [x] `/education` GET API: progress_all response 예시 값에 0이 아닌 double 값으로 변경
- [x] `/education` GET API: is_completed... 컬럼들 어떤 String 값이 오는지 response 설명 수정
- [x] 전체적으로 response가 리스트인 애들은 API 설명에 리스트임을 명시
- [x] `/education/quizzes` GET API: quizList responsedto 통일 → Quiz 테이블 하나로 정규화하기
- [x] `/education/lectures` GET API: Lecture 1개만 제공
