### ISSUE TITLE
Fix: /auth, /user API 수정

### ISSUE THREAD

**Issue by yejin9858** [CPR2U/CPR2U-Server#12]
## ☝️  Issue

/auth, /user API 수정

## 📃 To-do
- [x] /auth/verification : request에 device_token → phone_number
- [x]  /auth/signup : response에 user_roles 제거
- [x]  /auth/nickname: null 처리 확인이랑 닉네임 양식이 올바른지
- [x]  /auth/auto_login: response에 access_token 추가
- [x]  /users/address get API: response를 dto로 제공
- [x]  /users/address POST API: request 설명 달기
