### ISSUE TITLE
Feat: /auth API

### ISSUE THREAD

**Issue by yejin9858** [CPR2U/CPR2U-Server#2]
## ☝️  Issue
/auth 도메인 API 생성

## 📃 To-do

- [ ] /auth/signup API 생성
- [ ] /auth/code API 생성
- [ ] /auth/login proxy API 생성
