### ISSUE TITLE
Feat: GCP CI/CD 구축

### ISSUE THREAD

**Issue by raae7742** [CPR2U/CPR2U-Server#24]
## ☝️  Issue
Google Cloud Platform 배포 및 CI/CD 구축

## 📃 To-do
- [x] GCP 배포 환경 구축
- [x] CI/CD 구축
- [x] GCP 서버 배포 및 운영
