### ISSUE TITLE
Refactor: 테스트 코드 리팩토링

### ISSUE THREAD

**Issue by raae7742** [CPR2U/CPR2U-Server#53]
## ☝️  Issue
테스트용 H2 DB 연결
테스트 코드 리팩토링

## 📃 To-do
- [x] 테스트용 H2 DB 연결
- [ ] 전체적인 테스트 코드 리팩토링
- [x] 불필요한 Fake 객체 제거
