### ISSUE TITLE
Refactor: 전반적인 코드 리팩토링

### ISSUE THREAD

**Issue by yejin9858** [CPR2U/CPR2U-Server#55]
## ☝️  Issue

- 전반적인 솔챌 제출 코드 리팩토링

## 📃 To-do

- [ ] fcm 메세지 전송 코드 리팩토링
- [ ] 테스트 코드 테스트 경우 추가 및 리팩토링
- [ ] 그 외 코드도 읽어보고, 리팩토링 하기
